name: CI/CD

on: [push]

jobs:
  rspec:
    runs-on: ubuntu-latest
    env:
      PG_DATABASE: postgres
      PG_HOST: localhost
      PG_PORT: 5432
      PG_USER: postgres
      PG_PASSWORD: postgres
      RAILS_ENV: test
      YOUTUBE_API_KEY: ${{ secrets.YOUTUBE_API_KEY }}

    services:
      postgres:
        image: postgres
        env:
          POSTGRES_HOST_AUTH_METHOD: 'trust'
          POSTGRES_PASSWORD: postgres
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
        ports:
          - 5432:5432

    steps: 
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install 

      - name: db create
        run: bundle exec rails db:create db:schema:load

      - name: Run tests
        run: bundle exec rspec


  rubocop-airbnb:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.2.3
          bundler-cache: true

      - name: Bundler and gem install
        run: |
          gem install bundler
          bundle install 

      - name: Run rubocop-airbnb
        run: bundle exec rubocop --require rubocop-airbnb


  deploy:
    runs-on: ubuntu-latest
    needs: [rspec, rubocop-airbnb]
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        uses: akhileshns/heroku-deploy@v3.13.15
        with:
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "oshitube"
          heroku_email: ${{secrets.HEROKU_EMAIL}}
